# Config for EleutherEvalRecipe in eleuther_eval.py
#

# Model Arguments
model:
  _component_: torchtune.models.gemma.gemma_2b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/models/gemma-2b/
  checkpoint_files: [
    model-00001-of-00002.safetensors,
    model-00002-of-00002.safetensors,
  ]
  output_dir: ./models/
  model_type: GEMMA

# Tokenizer
tokenizer:
  _component_: torchtune.models.gemma.gemma_tokenizer
  path: /tmp/models/gemma-2b/tokenizer.model
  max_seq_len: null

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2"]
limit: null
max_seq_length: 4096
batch_size: 2
# It is recommended to set enable_kv_cache=False for long-context models like Llama3.1
enable_kv_cache: True

# Quantization specific args
quantizer: null
